# Generated by Django 5.0.6 on 2024-06-20 11:41

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_reorganized_user_model'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.ProfileManager()),
            ],
        ),
        migrations.AlterField(
            model_name='productinbasket',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
    ]
