# Generated by Django 5.0.6 on 2024-06-11 12:16

import datetime
import django.db.models.deletion
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_created_order_status_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.DecimalField(decimal_places=2, max_digits=9)),
                ('order_datetime', models.DateTimeField(default=datetime.datetime(2024, 6, 11, 15, 16, 10, 402558))),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.client')),
                ('order_status_id', models.ForeignKey(default=orders.models.OrderStatus.get_default_pk, on_delete=django.db.models.deletion.PROTECT, to='orders.orderstatus')),
            ],
        ),
    ]
