# Generated by Django 5.0.6 on 2024-06-11 14:46

import django.db.models.deletion
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_created_order_model_and_add_add_default_pk_to_order_status_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='client',
            name='patronymic_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status_id',
            field=models.ForeignKey(default=orders.models.OrderStatus.get_default_pk, on_delete=django.db.models.deletion.PROTECT, to='orders.orderstatus', verbose_name='Cтатус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='summary',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
