# Generated by Django 5.0.6 on 2024-06-11 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_rest_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_status_id',
            new_name='order_status',
        ),
        migrations.CreateModel(
            name='ShoppingBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Сумма')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.client', verbose_name='Клиент')),
            ],
        ),
    ]
