# Generated by Django 5.0.6 on 2024-06-12 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_edited_product_in_basket_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingbasket',
            name='summary',
        ),
    ]
