# Generated by Django 5.0.6 on 2024-06-16 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_added_connection_between_client_and_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.RemoveField(
            model_name='shoppingbasket',
            name='client',
        ),
        migrations.RemoveField(
            model_name='shoppingbasket',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productinstock',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productinbasket',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productinbasket',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='order',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='ProductInStock',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductInBasket',
        ),
        migrations.DeleteModel(
            name='ShoppingBasket',
        ),
        migrations.DeleteModel(
            name='ProductInOrder',
        ),
    ]
