# Generated by Django 5.0.6 on 2024-06-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_created_many_to_many_connection_beetween_products_and_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий к заказу'),
        ),
    ]
