# Generated by Django 5.0.6 on 2024-06-21 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_added_comment_field_to_oreder_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='client',
            new_name='user',
        ),
    ]
