# Generated by Django 5.0.6 on 2024-06-17 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_created_many_to_many_connection_beetween_products_and_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductInBasket',
        ),
    ]
